// Enum index mirrors of contracts/policy/PolicyTypes.sol, for readable tests.
module.exports = {
  Msp: {
    None: 0,
    Police: 1,
    Forensics: 2,
    Prosecution: 3,
    Court: 4,
    Audit: 5,
  },
  Role: {
    None: 0,
    Constable: 1,
    SubInspector: 2,
    Inspector: 3,
    Sho: 4,
    InvestigatingOfficer: 5,
    LabAnalyst: 6,
    LabDirector: 7,
    PublicProsecutor: 8,
    DefenseCounsel: 9,
    Judge: 10,
    Magistrate: 11,
    CourtClerk: 12,
    Auditor: 13,
    Ombudsman: 14,
  },
  RecordType: {
    None: 0,
    Fir: 1,
    CaseDiary: 2,
    Evidence: 3,
    ForensicReport: 4,
    WitnessStatement: 5,
    Chargesheet: 6,
    CourtOrder: 7,
  },
  Sensitivity: { Low: 0, Medium: 1, High: 2 },
  Action: { View: 0, Export: 1, Annotate: 2 },
  Purpose: {
    Unset: 0,
    Investigation: 1,
    ForensicAnalysis: 2,
    Prosecution: 3,
    JudicialProceeding: 4,
    AuditReview: 5,
    DefensePreparation: 6,
  },
  Clearance: { Unset: 0, Low: 1, Medium: 2, High: 3 },
  Decision: { Allow: 0, Deny: 1, Escalate: 2 },
  Status: {
    Granted: 0,
    Denied: 1,
    Pending: 2,
    Approved: 3,
    Rejected: 4,
  },
  POLICY_VERSION: "crime-policy-v1",
};
