#!/usr/bin/env bash
#
# Tear down the Crime Records Access Network and remove generated material.

set -uo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
NETWORK_DIR="${PROJECT_DIR}/network"

# Use whichever Docker runtime holds the Fabric images.
if ! docker image inspect hyperledger/fabric-peer:latest >/dev/null 2>&1; then
  for ctx in $(docker context ls --format '{{.Name}}' 2>/dev/null); do
    if docker --context "${ctx}" image inspect hyperledger/fabric-peer:latest >/dev/null 2>&1; then
      export DOCKER_CONTEXT="${ctx}"
      break
    fi
  done
fi

cd "${NETWORK_DIR}"

docker compose -f compose/compose-net.yaml -f compose/compose-ca.yaml down --volumes --remove-orphans 2>/dev/null

# Remove chaincode containers/images generated by peers on this network.
CC_CONTAINERS="$(docker ps -aq --filter name='dev-peer0' 2>/dev/null)"
[ -n "${CC_CONTAINERS}" ] && docker rm -f ${CC_CONTAINERS} >/dev/null 2>&1
CC_IMAGES="$(docker images -q --filter reference='dev-peer0*' 2>/dev/null)"
[ -n "${CC_IMAGES}" ] && docker rmi -f ${CC_IMAGES} >/dev/null 2>&1

# Remove generated crypto material and channel artifacts.
rm -rf "${NETWORK_DIR}/organizations/peerOrganizations" \
       "${NETWORK_DIR}/organizations/ordererOrganizations" \
       "${NETWORK_DIR}/organizations/fabric-ca" \
       "${NETWORK_DIR}/channel-artifacts"

echo "Crime Records Access Network torn down."
